MENTORING-T-69 알고리즘 과제
BI-kotlin-in-action/JoSeungBin pull request #3
Opened 2023-11-05 07:51 UTC by vkflco08

2023-11-06 14:57 UTC, konempty requested changes
크 이번주 문제 할당량은 2~3문제 문제 였는데 4문제 풀어오시다니 너무 좋습니다 👍 👍 
조금만더 수정 부탁드릴게요~!

2023-11-06 14:57 UTC, konempty commented on 11054.kt
> +    val minArr = Array(input) { 1 }
Int를 담는 Array라면 Array<Int>대신에 IntArray를 사용하는게 좋습니다~!

2023-11-06 14:57 UTC, konempty commented on 1159.kt
> +    val array = IntArray(26) { 0 }
IntArray는 기본적으로 0으로 초기화 되기때문에 { 0 }은 불필요한 코드입니다!

2023-11-06 14:57 UTC, konempty commented on 1159.kt
> +    for (i in 0..size - 1) {
여긴 until을 쓴다면 좋을것 같아요

2023-11-06 14:57 UTC, konempty commented on 1159.kt
> +        for (i in 0..array.size - 1) {
여기도 until이면 좋을것 같네요 ㅋㅋㅋ

2023-11-06 14:57 UTC, konempty commented on 12789.kt
> +import java.util.*
헉 와일드 카드 임포트는 지양하는게 좋습니다
https://blog.leocat.kr/notes/2020/12/14/intellij-avoid-wildcard-imports-in-kotlin-with-intellij
요 블로그 참고해서 설정해주세요!

2023-11-06 14:57 UTC, konempty commented on 12789.kt
> +    var N = 1
요 N을 굳이 대문자로 선언하신 이유가 궁금합니다~!

2023-11-06 14:57 UTC, konempty commented on 12789.kt
> +    while (!firstLine.isEmpty()) {
firstLine.isNotEmpty() 를 쓰는게 더 좋을것 같아요!
요 아래로도 비슷한 코드가 있는데 같이 적용 부탁드릴게요 ㅎㅎ

2023-11-06 14:57 UTC, konempty commented on 1931.kt
> +    var N = Array(input) { IntArray(2) }
2개의 엘리먼트만 담는다면 IntArray(2)보다는 코틀린의 Pair를 사용하는게 더 낫습니다

2023-11-07 13:12 UTC, konempty commented
ㅠㅠㅠ 제가 드린 질문에는 답변 부탁드릴게요..!
무작정 수정하라는게 아니라 성빈님의 의도가 궁금했던거예요

2023-11-07 13:20 UTC, konempty approved these changes
고생하셨습니다 👍 👍 
이번 코멘트 반영후 머지하셔도 좋을것 같습니다~!
다음부터는 제가 질문으로 달아두는건 무조건 수정하지 않으셔도 좋구요
어떤 의도의 코드였는지 설명부탁드릴게요!

2023-11-07 13:20 UTC, konempty commented on 12789.kt
> +    for (i in 0 until input) firstLine.add(inputList[i])
요기는

    firstLine.addAll(inputList)
요렇게 한번에 추가하시는게 효율적입니다~!

2023-11-07 13:20 UTC, konempty commented on 1931.kt
> +    var temp = sortedMeetings[0].second
temp라는 이름은 직관적이지 않은데
변수명을 지을땐 해당 변수가 어떤 역할을 수행하는지 알수있는 이름으로 지어주세요~!

2023-11-07 15:56 UTC, vkflco08 commented on 12789.kt
> +    var N = 1
문제에서 N이라고 나와있어서 대문자로 사용했습니다.

2023-11-07 16:03 UTC, merged